feat(resolve): pull out resolve helpers into @oazapfts/resolve
ref https://github.com/zoubingwu/msw-auto-mock/issues/106

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -99,6 +99,15 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
+      - name: 📦 Release @oazapfts/resolve
+        run: |
+          set -e  # Exit immediately if a command exits with a non-zero status.
+
+          cd packages/resolve
+          npx semantic-release
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
       - name: 📦 Release oazapfts
 
         run: |
